name: pydelmod
channels:
  - conda-forge
  - cadwr-dms
  - nodefaults
dependencies:
  - python<3.14
  - numpy
  - pip
  # pip install these
  - ipykernel
  # first our packages
  - pyhecdss
  - vtools3
  - schimpy
  - dms-datastore
  - pydsm
  - pydelmod
  # then basics
  - click
  - aiohttp
  - numba
  - dask
  - pandas
  - xarray
  - h5py
  - scipy
  # geo stuff
  # - pyogrio # causes schimpy to downgrade
  - geopandas
  # then plot stuff
  - plotly-orca
  - plotly
  - matplotlib
  - jupyter_bokeh
  - holoviews
  - geoviews
  - hvplot
  - networkx
  # for ui
  - panel
  # for different file formats
  - fastparquet
  - python-snappy
  - pyarrow
  - pytables
  - openpyxl
  - jinja2
  - diskcache
  # browsers
  - selenium
  - firefox
  - geckodriver
  # finally misc
  - lxml
  - black
  - tabulate
  #- pip:
  #  - -U kaleido # image export for plotly
# pip install pydelmod and pydsm from github. use the -e flag to install in editable mode as indicated below
#  - pip:
#     - -e git+https://github.com/CADWRDeltaModeling/pydelmod#egg=pydelmod
#     - -e git+https://github.com/CADWRDeltaModeling/pydsm#egg=pydsm

