name: pydelmod
channels:
  - cadwr-dms
  - plotly
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - cftime=1.0.4.2
  - chardet=3.0.4
  - colorama=0.4.3
  - cryptography=2.8
  - curl=7.68.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - inflect=4.1.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jaraco.itertools=5.0.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - krb5=1.17.1
  - libcurl=7.68.0
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.5.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - netcdf4=1.4.2
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - plotly=3.6.1
  - plotly-orca=1.2.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - psutil=5.6.7
  - pycparser=2.19
  - pydelmod
  - pygments=2.5.2
  - pyhecdss
  - pyopenssl=19.1.0
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qgrid=1.1.1
  - qt=5.9.7
  - qtconsole=4.6.0
  - requests=2.22.0
  - retrying=1.3.3
  - send2trash=1.5.0
  - setuptools=45.1.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=2.1.0
  - zlib=1.2.11

