name: dev_pydelmod
channels:
  - pyviz
  - defaults
  - cadwr-dms
  - conda-forge
dependencies:
  - python=3.7
  - pip
  # first our packages
  - pyhecdss
  - vtools3
  - pydsm
  # - pydelmod needs to pip install --no-deps -e
  - schimpy
  # then basics
  - numba
  - pandas
  - dask
  - xarray
  - netcdf4
  - scipy
  - gdal
  - shapely
  # for different file formats
  - fastparquet
  - python-snappy
  - pyarrow
  - pytables
  - openpyxl
  # then plot stuff
  - matplotlib
  - descartes
  - geopandas
  - geoviews
  - holoviews
  - hvplot
#  - jupyter_bokeh
  - jupyter
  - plotly-orca
  - plotly=3
  - networkx
  # widgets
  - ipyleaflet
  - ipywidgets
  # browsers
  - selenium
  - firefox
  - geckodriver
  # finally misc 
  - jupyter_contrib_nbextensions
  - autopep8
  - sphinx
  - pytest
  - pytest-runner
  - pdoc3
#  - pip : # not working with the no-deps option. Here for doc purposes. Run by hand
#    - --no-deps -e .

# To resolve issue with Fiona ("module 'fiona' has no attribute '_loading'"), run the following:
#   pip install fiona --no-deps --force-reinstall

# To resolve issue with Pillow ("DLL load failed"), run the following:
#   pip install Pillow --force-reinstall

# Once the environment is set up, install pydelmod using:
#   pip install -e .