name: dev_pydelmod
channels:
  - cadwr-dms
  - conda-forge
  - nodefaults
dependencies:
  - python<3.12
  - pip
  # pip install these
  - ipykernel
  # first our packages
  - pyhecdss
  - vtools3
  - schimpy
  - dms-datastore
  # then basics
  - click
  - aiohttp
  - numba
  - dask
  - pandas
  - xarray
  - h5py
  - scipy
  # geo stuff
  - geopandas
  # then plot stuff
  - plotly-orca
  - plotly
  - matplotlib
  - holoviews
  - geoviews
  - hvplot
  - networkx
  # for different file formats
  - fastparquet
  - python-snappy
  - pyarrow
  - pytables
  - openpyxl
  - jinja2
  # browsers
  - selenium
  - firefox
  - geckodriver
  # finally misc and dev related
  - black
  - sphinx
  - pytest
  - pytest-runner
  - pdoc3
# pip install pydelmod and pydsm from github. use the -e flag to install in editable mode as indicated below
#  - pip:
#     - -e git+https://github.com/CADWRDeltaModeling/pydelmod#egg=pydelmod
#     - -e git+https://github.com/CADWRDeltaModeling/pydsm#egg=pydsm
# Once the environment is set up, install pydelmod using:
#   pip install -e .