name: pydelmod
channels:
  - cadwr-dms
  - pyviz
  - defaults
  - plotly
  - conda-forge
dependencies:
  - python=3.7
  # first our packages
  - pyhecdss
  - vtools3
  - pydsm
  - pydelmod
  - schimpy
  # then basics
  - numba
  - dask
  - xarray
  - netcdf4
  - scipy
  - gdal
  - shapely
  - pytables
  # then plot stuff
  - matplotlib
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - jupyter
  - plotly=3
  - networkx
  - ipyleaflet
  - ipywidgets
  - selenium
  - firefox
  - geckodriver
  # finally misc 
  - jupyter_contrib_nbextensions
  - ipysheet
  - autopep8
