name: pydelmod
channels:
  - plotly
  - cadwr-dms
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - autopep8=1.4.4
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.15.0
  - bokeh=1.2.0
  - branca=0.3.1
  - bzip2=1.0.6
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - colorama=0.4.1
  - cryptography=2.6.1
  - curl=7.64.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.5
  - fiona=1.8.4
  - flask=1.1.1
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.3.3
  - geopandas=0.4.1
  - geos=3.7.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - holoviews=1.12.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipyleaflet=0.10.2
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - itsdangerous=1.1.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - kealib=1.4.7
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.64.1
  - libgdal=2.3.3
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.16
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - libxslt=1.1.32
  - lxml=4.3.3
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.0.1
  - markdown=3.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - msys2-conda-epoch=20160418
  - munch=2.3.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - netcdf4=1.4.2
  - nodejs=10.13.0
  - notebook=5.7.8
  - numexpr=2.6.9
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - openssl=1.1.1c
  - orca=1.5.1
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - panel=0.5.1
  - param=1.9.0
  - parso=0.4.0
  - pcre=8.43
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - plotly=3.10.0
  - plotly-orca=1.2.1
  - proj4=5.2.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - psycopg2=2.7.6.1
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pygments=2.4.0
  - pyhecdss=0.2.5
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.7.0
  - pytables=3.5.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyviz_comms=0.7.2
  - pywinpty=0.5.5
  - pyyaml=5.1
  - pyzmq=18.0.0
  - qgrid=1.1.1
  - qt=5.9.7
  - qtconsole=4.4.4
  - requests=2.21.0
  - retrying=1.3.3
  - rtree=0.8.3
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - sqlalchemy=1.3.4
  - sqlite=3.28.0
  - terminado=0.8.2
  - testpath=0.3.1
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.2
  - traitlets=4.3.2
  - traittypes=0.2.1
  - urllib3=1.24.2
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.5
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xarray=0.12.1
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7

