name: pydelmod
channels:
  - cadwr-dms
  - pyviz
  - defaults
  - plotly
  - conda-forge
dependencies:
  - python=3.7
  - pip
  # first our packages
  - pyhecdss
  - vtools3
  - pydsm
  - pydelmod
  - schimpy
  # then basics
  - click
  - aiohttp
  - numba
  - pandas
  - dask
  - xarray
  - netcdf4
  - scipy
  # geo stuff
  - gdal
  - shapely
  - geopandas
  # for different file formats
  - fastparquet
  - python-snappy
  - pyarrow
  - pytables
  - openpyxl
  # then plot stuff
  - matplotlib
  - geoviews
  - holoviews
  - hvplot
  - jupyter
  - plotly-orca
  - plotly
  - networkx
  # widgets
  - ipyleaflet
  - ipywidgets
  # browsers
  - selenium
  - firefox
  - geckodriver
  # finally misc 
  - jupyter_contrib_nbextensions
  - autopep8
