name: pydelmod
channels:
  - conda-forge
  - cadwr-dms
#  - pyviz
#  - defaults
#  - plotly
dependencies:
  - python=3.8
  - pip
  # first our packages
  - pyhecdss
  - vtools3
  - pydsm
  - pydelmod
  - schimpy
  # then basics
  - click
  - aiohttp
  - numba
  - pandas
  - dask
  - xarray
  - netcdf4
  - scipy
  # geo stuff
  - gdal
  - shapely
  - geopandas
  # for different file formats
  - fastparquet
  - python-snappy
  - pyarrow
  - pytables
  - openpyxl
  # then plot stuff
  - matplotlib
  - geoviews
  # later versions are not compatible with the current geoviews
#  - holoviews=1.14.7
#  - jinja2=3.0.3
  - holoviews
  - jinja2
  - hvplot
  - jupyter
  - plotly-orca
  - plotly
  - networkx
  # widgets
  - ipyleaflet
  - ipywidgets
  # browsers
  - selenium
  - firefox
  - geckodriver
  # finally misc 
  - jupyter_contrib_nbextensions
  - autopep8
