output_locations: "info/DSM2_ec_loc_stds.csv"
scenarios:
  - name: "1ex_2020"
    fpath: "scenarios/1ex_2020_EC_p.dss"
  - name: "7pp_2020"
    fpath: "scenarios/7pp_2020_EC_p.dss"
variable: "EC-MEAN"
interval: "1DAY"
calsim_file: "scenarios/calsim.dss"
delta_standards:
  - name: "D1641 AG WI"
    fpath: "info/D1641_AG_wiDelta.csv"
    variable: "EC-MEAN-14DAY"
  - name: "D1641 AG South"
    fpath: "info/D1641_AG_sDelta.csv"
    variable: "EC-MEAN-30DAY"
  - name: "D1641 AG Export"
    fpath: "info/D1641_AG_export.csv"
    variable: "EC-MEAN-30DAY"
  - name: "D1641 FWS SJR"
    fpath: "info/D1641_FWS_SJR.csv"
    variable: "EC-MEAN-14DAY"
  - name: "D1641 FWS Suisun"
    fpath: "info/D1641_FWS_Suisun.csv"
    variable: "EC-MAX-MEAN"
  - name: "D1641 MI 250"
    fpath: "info/D1641_MI_250.csv"
    variable: "Chloride-MEAN"
  - name: "D1641 MI 150"
    fpath: "info/D1641_MI_150.csv"
    variable: "Chloride-MEAN"
  #- name: "D1641 FWS Suisun1"
  #  fpath: "info/D1641_FWS_Suisun1.csv"
  #  variable: "EC-HT-MEAN"
  #  interval: "1DAY"
period: 
  - "1921-01-01"
  - "2021-09-30"
plots:
  - type: "plot_step_w_regulation"
    options:
      yaxis_name: "14-day running average EC - standard (mmhos/cm)"
      title: "EC 14-Day Mean for D1641_AG West&Interior Delta Timelines"
      delta_standard: "D1641 AG WI"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "14-day running average EC - standard (mmhos/cm)"
      title: "EC 14-Day Mean for D1641_AG West&Interior Delta Exceedances"
      delta_standard: "D1641 AG WI"
  - type: "plot_step_w_regulation"
    options:
      yaxis_name: "30-day running average EC - standard (mmhos/cm)"
      title: "EC 30-Day Mean for D1641_AG South Delta Timelines"
      delta_standard: "D1641 AG South"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "30-day running average EC - standard (mmhos/cm)"
      title: "EC 30-Day Mean for D1641_AG South Delta Exceedances"
      delta_standard: "D1641 AG South"
  - type: "plot_step_w_regulation"
    options:
      yaxis_name: "30-day running average EC - standard (mmhos/cm)"
      title: "EC 30-Day Mean for D1641_AG Export Timelines"
      delta_standard: "D1641 AG Export"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "30-day running average EC - standard (mmhos/cm)"
      title: "EC 30-Day Mean for D1641_AG Export Exceedances"
      delta_standard: "D1641 AG Export"
  - type: "plot_step_w_regulation"  
    options:
      yaxis_name: "14-day running average EC - standard (mmhos/cm)"
      title: "EC 14-Day Mean for D1641_FWS San Joaquin River Timelines"
      delta_standard: "D1641 FWS SJR"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "14-day running average EC - standard (mmhos/cm)"
      title: "EC 14-Day Mean for D1641_FWS San Joaquin River Exceedances"
      delta_standard: "D1641 FWS SJR"
  - type: "plot_step_w_regulation"
    options:
      yaxis_name: "EC Monthly Mean of Daily Max (mmhos/cm)"
      title: "EC Monthly Mean of Daily Max for D1641_FWS Suisun Timelines"
      delta_standard: "D1641 FWS Suisun"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "Diff in EC scenario-standard (mmhos/cm)"
      title: "EC Monthly Mean of Daily Max for D1641_FWS Suisun Exceedances"
      delta_standard: "D1641 FWS Suisun"
  - type: "plot_step_w_regulation"
    options:
      yaxis_name: "Chloride Daily (mg/L)"
      title: "Chloride Daily for D1641 MI 250 Timelines"
      delta_standard: "D1641 MI 250"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "Chloride Daily -standard (mg/L)"
      title: "Chloride Daily for D1641 MI 250 Exceedances"
      delta_standard: "D1641 MI 250"
  - type: "plot_step_w_regulation"
    options:
      yaxis_name: "Number of days in year under regulation (day)"
      title: "Yearly number of days for D1641 MI 150 Timelines"
      delta_standard: "D1641 MI 150"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "Number of days under regulation - standard (day)"
      title: "Yearly number of days for D1641 MI 150 Exceedances"
      delta_standard: "D1641 MI 150"
  - type: "plot_step_w_variable_station_filters"
    options:
      yaxis_name: "Daily Mean EC (mmhos/cm)"
      title: "EC Daily Mean Timelines"
  - type: "plot_bar_monthly_w_controls"
    options:
      yaxis_name: "Daily Mean EC (mmhos/cm)"
      title: "EC Monthly Barcharts of Daily Mean"
  - type: "plot_exceedance_w_variable_station_filters"
    options:
      yaxis_name: "Daily Mean EC (mmhos/cm)"
      title: "EC Daily Mean Exceedances"
  - type: "plot_box_w_variable_station_filters"
    options:
      yaxis_name: "Daily Mean EC (mmhos/cm)"
      title: "EC Daily Mean Box-Whiskers"
