{% set name = "pydelmod" %}
{% set version = environ.get('VERSION', '') %}
{% if version == '' %}
  {% set version = "0.0.0.dev" %}
{% endif %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ version }}"

source:
  #git_url: https://github.com/CADWRDeltaModeling/pydelmod.git
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pydelmod = pydelmod.cli:main
  include_recipe: False
  preserve_egg_dir: True

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=64.0
    - setuptools_scm >=7.0
    - wheel
  run:
    - python >=3.7
    # Add your dependencies here manually since we can't load from setup.py
    # If you had dependencies in setup.py, list them explicitly here


test:
  imports:
    - pydelmod
  requires:
    - pytest
  
files:
  - pydelmod/dvue/dataui.noselection.html

about:
  home:           "https://github.com/CADWRDeltaModeling/pydelmod"
  license: MIT
  license_file: LICENSE
  summary:        "Python package to work with Delta Modeling tasks"
